# syntax = docker/dockerfile:1.2
FROM python:3.8.13-slim-bullseye

# build packages
RUN apt-get update && apt-get install -y build-essential libcurl4-nss-dev libssl-dev curl

# poetry
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.1.4 \
    POETRY_HOME="/opt/poetry" \
    POETRY_NO_INTERACTION=1

ENV PATH=$POETRY_HOME/bin:$PATH
RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python -
RUN chmod 777 $POETRY_HOME/bin/poetry

# install dependencies
COPY pyproject.toml ./
#COPY batch/src/app.py ./
COPY __init__.py ./
RUN ["echo", "hello world"]
